import Link from 'next/link';

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-200 selection:bg-indigo-500/30">
      <div className="max-w-4xl mx-auto px-6 py-24">
        <h1 className="text-5xl font-bold tracking-tight text-white mb-6">Psychosynth API</h1>
        <p className="text-xl text-slate-400 mb-12 max-w-2xl leading-relaxed">
          Synthetic psychometric data generation and curation. High-fidelity synthetic personalities for behavioral simulations and ML training, powered by the Five-Factor Model.
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
          <div className="p-8 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl">
            <h2 className="text-xl font-semibold text-white mb-3">API Access</h2>
            <p className="text-slate-400 mb-6 leading-relaxed">Integrate pre-curated datasets into your systems via the x402 protocol. Free catalog and preview; paid queries settle in USDC on Base.</p>
            <code className="block p-4 bg-slate-950 rounded-lg text-sm text-indigo-400 font-mono border border-slate-800/50">
              GET /api/v1/query/personality-profile-library
            </code>
            <a href="/docs" className="mt-4 inline-block text-sm text-indigo-400 hover:text-indigo-300 font-medium">
              Read the API docs &rarr;
            </a>
          </div>
          <div className="p-8 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl flex flex-col items-start">
            <h2 className="text-xl font-semibold text-white mb-3">The Lab</h2>
            <p className="text-slate-400 mb-8 leading-relaxed">Internal tooling for prompt engineers and behavioral scientists to curate data.</p>
            <Link href="/lab" className="mt-auto inline-flex items-center px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition-colors shadow-lg shadow-indigo-500/20">
              Enter Lab &rarr;
            </Link>
          </div>
        </div>

        <section className="prose prose-invert max-w-none">
          <h3 className="text-2xl font-bold text-white mb-6 border-b border-slate-800 pb-4">Methodology</h3>
          <p className="text-slate-400 text-lg mb-6">All synthetic profiles undergo a strict curation loop:</p>
          <ul className="space-y-3 text-slate-300 list-disc list-inside bg-slate-900/50 p-6 rounded-xl border border-slate-800/50">
            <li>Generated by schema-constrained LLM calls, grounded in the Five-Factor Model (IPIP-NEO framing).</li>
            <li>Validated against the generator&apos;s strict JSON Schema — invalid items are rejected, never patched.</li>
            <li>Deduplicated with pg_trgm trigram similarity against the approved corpus.</li>
            <li>Human-reviewed in the Curation Cockpit; every edit is versioned with fresh provenance hashes.</li>
            <li>All data is synthetic (<code className="text-indigo-400">synthetic: true</code> in every payload) — no real persons, no PII.</li>
          </ul>
          <p className="text-slate-500 text-sm mt-6">
            Per-product methodology: <a href="/methodology/big-five-profile-gen" className="text-indigo-400 hover:text-indigo-300">/methodology/big-five-profile-gen</a>
          </p>
        </section>
      </div>
    </main>
  );
}
