'use strict';
/*
 * Psychosynth v4 — archetype data for the persona pipeline.
 *
 * Three exports:
 *  - LEGACY_ARCH: the 22 retail/trading archetypes already established by
 *    scripts/gen-bulk-seed.mjs (same anchors, same behavioral banks — kept so
 *    the archetype taxonomy stays stable across batches; the v4 composer
 *    weaves these fragments into new frame structures, so output text does
 *    not collide with earlier one-liner summaries).
 *  - NEW_ARCH: 22 fresh archetypes (solana/defi/whale/retail/negotiation/kol)
 *    with newly authored banks — the "original fresh" material of this round.
 *  - V3_REPAIR: per-archetype banks used to rewrite the 15 template-stamped
 *    v3 batches in place (SQL-side composition; see 04_repair_v3_profiles.sql).
 *
 * dt = dark-triad anchors {m: machiavellianism, n: narcissism, p: psychopathy}.
 * lam = loss-aversion lambda anchor. All anchors get seeded per-row jitter.
 */

const LEGACY_ARCH = [
 {tag:'panic-seller',style:'avoidant',lam:2.7,dt:{m:.32,n:.30,p:.20},bf:{openness:.45,conscientiousness:.38,extraversion:.42,agreeableness:.55,neuroticism:.80},bias:['loss-aversion','ostrich-effect','negativity'],
  entry:['enters cautiously and small','waits for obvious confirmation before buying','sizes down after any scare'],stress:['bails at the first sign of red','liquidates into any sharp drawdown','freezes then dumps at the lows'],tell:['checks the P&L compulsively','cannot look when the book is red','sleeps badly holding risk overnight'],packs:['robinhood']},
 {tag:'revenge-trader',style:'spontaneous',lam:2.5,dt:{m:.55,n:.62,p:.58},bf:{openness:.55,conscientiousness:.30,extraversion:.62,agreeableness:.38,neuroticism:.76},bias:['loss-aversion','sunk-cost','escalation-of-commitment'],
  entry:['sizes up quickly after a loss','trades bigger to get even','re-enters immediately after a stop-out'],stress:['doubles down on losers to justify the entry','chases the loss with more size','abandons the plan when behind'],tell:['trades hardest right after a stop-out','confuses being right with being whole','treats the market as a personal opponent'],packs:['robinhood']},
 {tag:'meme-chaser',style:'spontaneous',lam:1.4,dt:{m:.42,n:.66,p:.44},bf:{openness:.85,conscientiousness:.30,extraversion:.76,agreeableness:.46,neuroticism:.60},bias:['fomo','herd-behavior','recency'],
  entry:['chases whatever is trending','enters late into parabolic moves','buys the loudest ticker in the feed'],stress:['adds into the vertical move','refuses to miss the run','holds through the top expecting more'],tell:['trades the feed, not the thesis','lives for the excitement','narrates every position online'],packs:['robinhood','solana']},
 {tag:'disciplined-swing',style:'analytical',lam:1.9,dt:{m:.30,n:.34,p:.22},bf:{openness:.60,conscientiousness:.82,extraversion:.45,agreeableness:.52,neuroticism:.34},bias:['confirmation','anchoring'],
  entry:['enters on a rules-based signal','sizes consistently against a plan','waits for the setup without forcing it'],stress:['honors predefined stops','trims into strength by rule','sits out when conditions are unclear'],tell:['over-weights confirming evidence','journals every trade','reviews mistakes methodically'],packs:['robinhood']},
 {tag:'options-gambler',style:'spontaneous',lam:1.3,dt:{m:.58,n:.70,p:.62},bf:{openness:.80,conscientiousness:.34,extraversion:.70,agreeableness:.36,neuroticism:.64},bias:['overconfidence','gamblers-fallacy','illusion-of-control'],
  entry:['buys short-dated options for the payoff','bets on the binary event','swings for the fences on conviction'],stress:['expects a reversal after any streak','presses the bet when it moves','rolls losers into more leverage'],tell:['overrates its own edge','treats variance as skill','remembers the wins, forgets the zeros'],packs:['robinhood']},
 {tag:'conservative-hodler',style:'deliberative',lam:2.2,dt:{m:.24,n:.26,p:.16},bf:{openness:.44,conscientiousness:.80,extraversion:.36,agreeableness:.62,neuroticism:.30},bias:['status-quo','endowment'],
  entry:['buys quality and holds','rarely trades, adds slowly','accumulates on a schedule'],stress:['sits through volatility unmoved','is slow to rebalance even when it helps','ignores short-term noise entirely'],tell:['values the position above the market','prefers the current allocation','tunes out the daily tape'],packs:['robinhood']},
 {tag:'copy-trader',style:'dependent',lam:1.8,dt:{m:.36,n:.44,p:.30},bf:{openness:.45,conscientiousness:.46,extraversion:.58,agreeableness:.72,neuroticism:.58},bias:['herd-behavior','authority-bias','bandwagon'],
  entry:['mirrors popular traders','enters when the accounts it follows do','waits for a signal from someone it trusts'],stress:['exits a beat behind the crowd','defers to loud authority','panics when the leader goes quiet'],tell:['trades social proof over analysis','always a step late','cannot articulate its own thesis'],packs:['robinhood','solana']},
 {tag:'news-reactor',style:'intuitive',lam:2.1,dt:{m:.40,n:.48,p:.38},bf:{openness:.60,conscientiousness:.40,extraversion:.66,agreeableness:.50,neuroticism:.68},bias:['recency','availability','gaze-heuristic'],
  entry:['trades the headline reflexively','reacts before the dust settles','front-runs its own interpretation'],stress:['overweights the latest vivid story','flips on every new print','whipsaws on conflicting reports'],tell:['anchors to whatever is most recent','mistakes noise for signal','trades the emotion of the news'],packs:['robinhood']},
 {tag:'scalper',style:'intuitive',lam:1.7,dt:{m:.44,n:.40,p:.42},bf:{openness:.55,conscientiousness:.66,extraversion:.60,agreeableness:.42,neuroticism:.55},bias:['recency','disposition-effect'],
  entry:['scalps intraday for small edges','takes many quick shots','works the order book for ticks'],stress:['cuts winners early for small gains','occasionally lets a loser run','over-trades a quiet session'],tell:['realizes gains too fast','holds losers hoping for scratch','burns out after a hot streak'],packs:['robinhood']},
 {tag:'yield-chaser',style:'dependent',lam:1.9,dt:{m:.38,n:.42,p:.34},bf:{openness:.52,conscientiousness:.58,extraversion:.50,agreeableness:.55,neuroticism:.52},bias:['herd-behavior','authority-bias','optimism'],
  entry:['chases the highest advertised yield','trusts popular picks','reaches for return over safety'],stress:['ignores the underlying risk for the number','follows the loudest expert','stays in too long for the carry'],tell:['confuses yield with safety','reaches for return','underprices tail risk'],packs:['defi']},
 {tag:'contrarian',style:'analytical',lam:2.0,dt:{m:.50,n:.46,p:.30},bf:{openness:.72,conscientiousness:.68,extraversion:.40,agreeableness:.40,neuroticism:.40},bias:['confirmation','overconfidence'],
  entry:['fades the crowd deliberately','buys what others are dumping','takes the unpopular side'],stress:['adds as the crowd presses against it','mistakes being early for being wrong','holds conviction past the evidence'],tell:['enjoys being the lone voice','distrusts consensus reflexively','anchors to a bearish or bullish identity'],packs:['robinhood']},
 {tag:'momentum-rider',style:'intuitive',lam:1.6,dt:{m:.40,n:.52,p:.44},bf:{openness:.66,conscientiousness:.56,extraversion:.64,agreeableness:.46,neuroticism:.48},bias:['recency','hot-hand','herd-behavior'],
  entry:['buys strength and sells weakness','rides trends until they break','adds to winners'],stress:['gives back gains at the turn','overstays the trend','confuses a pause for a reversal'],tell:['loves a strong chart','hates sitting in cash','extrapolates the last leg'],packs:['robinhood','solana']},
 {tag:'value-hunter',style:'deliberative',lam:2.1,dt:{m:.30,n:.30,p:.20},bf:{openness:.64,conscientiousness:.78,extraversion:.38,agreeableness:.56,neuroticism:.36},bias:['anchoring','confirmation','endowment'],
  entry:['buys on a valuation gap','builds a position patiently','waits years for the thesis'],stress:['averages down on falling knives','anchors to intrinsic value','ignores momentum entirely'],tell:['quotes multiples from memory','distrusts hype','holds through deep drawdowns'],packs:['robinhood']},
 {tag:'day-gambler',style:'spontaneous',lam:1.2,dt:{m:.52,n:.66,p:.60},bf:{openness:.70,conscientiousness:.28,extraversion:.72,agreeableness:.38,neuroticism:.66},bias:['gamblers-fallacy','illusion-of-control','overconfidence'],
  entry:['opens the app looking for action','bets on gut most mornings','sizes by mood'],stress:['chases every intraday swing','tilts after a red morning','revenge-sizes to get back to flat'],tell:['cannot sit flat','treats it like a casino','measures the day by dopamine'],packs:['robinhood']},
 {tag:'risk-manager',style:'analytical',lam:2.4,dt:{m:.28,n:.24,p:.18},bf:{openness:.58,conscientiousness:.86,extraversion:.40,agreeableness:.54,neuroticism:.34},bias:['zero-risk','ambiguity-aversion'],
  entry:['sizes by volatility and stop distance','never risks more than a fixed fraction','pre-defines the exit before entry'],stress:['cuts fast and small when wrong','reduces gross into uncertainty','protects capital above all'],tell:['thinks in R-multiples','sleeps fine flat','treats survival as job one'],packs:['robinhood']},
 {tag:'fomo-buyer',style:'spontaneous',lam:1.5,dt:{m:.36,n:.60,p:.40},bf:{openness:.74,conscientiousness:.34,extraversion:.72,agreeableness:.50,neuroticism:.62},bias:['fomo','bandwagon','recency'],
  entry:['buys after the move has run','fears missing the next leg','enters on social momentum'],stress:['adds at the highs','cannot wait for a pullback','sells at the lows in regret'],tell:['watches everyone else’s gains','buys tops, sells bottoms','trades to relieve anxiety'],packs:['robinhood','solana']},
 {tag:'diamond-hands',style:'deliberative',lam:2.6,dt:{m:.34,n:.50,p:.28},bf:{openness:.60,conscientiousness:.62,extraversion:.48,agreeableness:.52,neuroticism:.44},bias:['sunk-cost','endowment','loss-aversion'],
  entry:['commits to a conviction hold','ignores volatility on purpose','buys the dip on principle'],stress:['refuses to sell at any loss','treats holding as identity','doubles down through drawdowns'],tell:['wears the loss as a badge','distrusts anyone who sells','anchors to the entry price'],packs:['robinhood','solana']},
 {tag:'algo-fader',style:'analytical',lam:1.8,dt:{m:.46,n:.38,p:.40},bf:{openness:.70,conscientiousness:.74,extraversion:.42,agreeableness:.44,neuroticism:.40},bias:['overconfidence','clustering-illusion'],
  entry:['trades a systematic edge','sizes by backtested expectancy','removes discretion where it can'],stress:['overrides the system under stress','sees signal in noise','tinkers with a working model'],tell:['trusts the numbers over the gut','distrusts stories','fights the urge to intervene'],packs:['robinhood']},
 {tag:'social-trader',style:'dependent',lam:1.7,dt:{m:.34,n:.54,p:.34},bf:{openness:.62,conscientiousness:.44,extraversion:.78,agreeableness:.64,neuroticism:.54},bias:['herd-behavior','bandwagon','authority-bias'],
  entry:['trades what the community trades','enters on group hype','seeks confirmation before acting'],stress:['sells when the chat turns fearful','defers to the loudest voice','needs reassurance to hold'],tell:['posts every trade','trades for belonging','cannot hold a lonely position'],packs:['robinhood','solana']},
 {tag:'perfectionist',style:'deliberative',lam:2.3,dt:{m:.30,n:.44,p:.22},bf:{openness:.66,conscientiousness:.88,extraversion:.36,agreeableness:.54,neuroticism:.50},bias:['ambiguity-aversion','information-bias'],
  entry:['waits for the perfect setup','over-researches before acting','rarely pulls the trigger'],stress:['misses the move over-analyzing','second-guesses after entry','needs certainty that never comes'],tell:['always one more data point','regrets the trades not taken','treats a loss as a personal failure'],packs:['robinhood']},
 {tag:'whale-watcher',style:'intuitive',lam:1.8,dt:{m:.46,n:.50,p:.44},bf:{openness:.64,conscientiousness:.52,extraversion:.58,agreeableness:.46,neuroticism:.52},bias:['authority-bias','availability','herd-behavior'],
  entry:['follows large-wallet flows','front-runs perceived smart money','trades on on-chain signals'],stress:['chases a whale into a trap','over-reads a single transfer','flips on the next big move'],tell:['watches the order flow obsessively','trusts size over thesis','narrates what the whales must know'],packs:['solana','defi']},
 {tag:'set-and-forget',style:'deliberative',lam:2.0,dt:{m:.26,n:.28,p:.18},bf:{openness:.50,conscientiousness:.76,extraversion:.34,agreeableness:.60,neuroticism:.32},bias:['status-quo','default-effect','omission'],
  entry:['dollar-cost-averages on autopilot','sets it and ignores it','automates contributions'],stress:['does nothing through volatility','forgets to rebalance for months','tunes out drawdowns by design'],tell:['checks the account quarterly at most','prefers rules to decisions','treats inaction as strategy'],packs:['robinhood']},
];

// ---------------------------------------------------------------------------
// NEW v4 archetypes — freshly authored banks.
// theme: 'retail' | 'solana' | 'defi' | 'whale' | 'negotiation' | 'kol'
// ---------------------------------------------------------------------------
const NEW_ARCH = [
 // --- retail (Robinhood pack) ---
 {tag:'dip-buyer-dca',theme:'retail',style:'deliberative',lam:2.0,dt:{m:.26,n:.32,p:.18},bf:{openness:.52,conscientiousness:.72,extraversion:.42,agreeableness:.60,neuroticism:.42},bias:['anchoring','optimism','status-quo'],
  entry:['buys every scheduled dip like a standing order from their better self','adds a fixed slice whenever the index is red','treats a down day as a coupon, within reason'],
  stress:['keeps buying the ladder down until the cash runs out','stops looking at the average cost once it turns embarrassing','moves the "generational bottom" call one level lower each week'],
  tell:['quotes their cost basis like a birthday','believes in the long run with a horizon that keeps shortening','owns a mug about buying the dip and no mug about selling']},
 {tag:'earnings-lottery-player',theme:'retail',style:'spontaneous',lam:1.1,dt:{m:.48,n:.64,p:.56},bf:{openness:.78,conscientiousness:.30,extraversion:.68,agreeableness:.40,neuroticism:.58},bias:['overconfidence','availability','gamblers-fallacy'],
  entry:['buys weeklies into every earnings print that trended on the feed','plays the binary event for the story as much as the payout','picks the strike by round number and vibes'],
  stress:['rolls the busted lottery ticket into next week’s drawing','doubles the position to make the comeback story better','swears off earnings plays every quarter, for one week'],
  tell:['remembers the one 40-bagger with perfect clarity','narrates implied volatility without pricing it','celebrates the win before the print']},
 {tag:'tax-loss-harvester',theme:'retail',style:'analytical',lam:2.3,dt:{m:.40,n:.30,p:.20},bf:{openness:.56,conscientiousness:.84,extraversion:.36,agreeableness:.50,neuroticism:.38},bias:['framing','mental-accounting','anchoring'],
  entry:['buys with one eye on the exit’s tax treatment','pairs every speculative buy with a harvestable twin','sizes positions to keep the ledger tidy in December'],
  stress:['sells the loser on schedule and repurchases the feeling elsewhere','reframes a bad year as an efficient one','optimizes the wash-sale calendar harder than the thesis'],
  tell:['knows the code section but not the CEO’s name','treats losses as inventory','keeps a folder named HARVEST with color coding']},
 {tag:'stop-loss-phobe',theme:'retail',style:'avoidant',lam:3.1,dt:{m:.28,n:.34,p:.18},bf:{openness:.44,conscientiousness:.42,extraversion:.40,agreeableness:.58,neuroticism:.78},bias:['ostrich-effect','loss-aversion','disposition-effect'],
  entry:['enters without a stop because stops make it real','buys half now and promises the plan later','waits until the chart stops being scary, then waits more'],
  stress:['deletes the app for exactly one red day','converts a trade into an investment at minus twenty percent','checks the price through squinted eyes at 2am'],
  tell:['has never once been stopped out, technically','calls it a long-term hold in a tone that closes the topic','keeps a mental stop that has moved eleven times']},
 {tag:'paper-hands-scalper',theme:'retail',style:'intuitive',lam:2.6,dt:{m:.34,n:.44,p:.30},bf:{openness:.58,conscientiousness:.48,extraversion:.62,agreeableness:.52,neuroticism:.66},bias:['disposition-effect','loss-aversion','recency'],
  entry:['takes quick entries with quicker exits pre-loaded','buys strength and sells the first wobble','sets the take-profit closer than the stop, always'],
  stress:['sells the winner at plus two percent and watches it double from the sidelines','locks the tiny green before it can turn on them','exits everything before any scheduled announcement, always'],
  tell:['screenshot history is all small wins','narrates the ones that got away by exact percentage','feels a profit isn’t real until it’s realized, hourly']},
 {tag:'buy-the-rumor-flipper',theme:'retail',style:'intuitive',lam:1.6,dt:{m:.56,n:.52,p:.44},bf:{openness:.72,conscientiousness:.50,extraversion:.60,agreeableness:.42,neuroticism:.52},bias:['recency','confabulation','framing'],
  entry:['front-runs announcements that are still half-rumor','positions for the event and plans to leave before it','buys the setup narrative while it is still being drafted'],
  stress:['sells into the news pop with mechanical relief','bails the instant the story stops improving','flips direction if the rumor mutates'],
  tell:['reads timing as the whole edge','has no opinion on the company, only the calendar','collects catalysts like coupons']},
 // --- solana / defi ---
 {tag:'airdrop-farmer',theme:'solana',style:'analytical',lam:1.5,dt:{m:.62,n:.44,p:.38},bf:{openness:.74,conscientiousness:.70,extraversion:.44,agreeableness:.40,neuroticism:.44},bias:['optimism','planning-fallacy','sunk-cost'],
  entry:['grinds eligibility checklists across ten wallets before breakfast','farms points programs like a shift job','bridges dust everywhere the incentives point'],
  stress:['keeps farming a dead protocol because the points might still count','re-runs the sybil-risk math after every rule change','holds the claim past the dump window out of loyalty to the grind'],
  tell:['measures effort in transactions, not hours','knows every snapshot rumor by heart','values the unvested points above the vested balance']},
 {tag:'liquidity-sniper',theme:'solana',style:'spontaneous',lam:0.9,dt:{m:.70,n:.58,p:.66},bf:{openness:.82,conscientiousness:.46,extraversion:.64,agreeableness:.28,neuroticism:.48},bias:['overconfidence','action-bias','illusion-of-control'],
  entry:['snipes new pools in the first block they exist','pays priority fees like rent for being first','buys before the name has a website'],
  stress:['exits into the crowd it helped attract','cuts a failed snipe without ceremony and reloads','treats a honeypot loss as a tooling problem, not a lesson'],
  tell:['counts latency in slots','keeps a burner wallet museum of rugs survived','celebrates entries, never holds']},
 {tag:'rug-survivor',theme:'solana',style:'deliberative',lam:3.0,dt:{m:.38,n:.36,p:.26},bf:{openness:.56,conscientiousness:.64,extraversion:.42,agreeableness:.44,neuroticism:.70},bias:['negativity','availability','ambiguity-aversion'],
  entry:['reads the contract before the chart, twice','sizes every new position like it might vanish overnight','demands locked liquidity and still doubts it'],
  stress:['pulls everything at the first anomalous transfer','assumes the team wallet moving means the end','keeps post-mortems of every rug in a pinned note'],
  tell:['opens every thesis with the 2022 story','trusts audits the way sailors trust calm seas','keeps eighty percent in the same three majors']},
 {tag:'validator-loyalist',theme:'solana',style:'dependent',lam:2.1,dt:{m:.28,n:.36,p:.20},bf:{openness:.54,conscientiousness:.68,extraversion:.48,agreeableness:.68,neuroticism:.42},bias:['in-group','authority-bias','endowment'],
  entry:['stakes with the same operators through everything','buys the ecosystem, not the token','follows core-team wallets like weather'],
  stress:['holds through outages on principle','defends the network before checking the facts','restakes the drawdown as a statement'],
  tell:['wears the merch to family events','measures loyalty in epochs','takes criticism of the chain a little personally']},
 {tag:'perp-funding-farmer',theme:'defi',style:'analytical',lam:1.8,dt:{m:.52,n:.34,p:.30},bf:{openness:.66,conscientiousness:.80,extraversion:.36,agreeableness:.44,neuroticism:.36},bias:['zero-risk','pseudocertainty','mental-accounting'],
  entry:['harvests funding-rate spreads with hedged legs','enters only when the carry math clears fees twice over','automates the basis trade and babysits the automation'],
  stress:['unwinds instantly when the spread inverts','fears the depeg more than the drawdown','stress-tests the hedge nightly and sleeps anyway'],
  tell:['calls it fixed income with extra steps','quotes annualized numbers to two decimals','treats directional traders as tourists']},
 {tag:'governance-raider',theme:'defi',style:'analytical',lam:1.4,dt:{m:.82,n:.60,p:.58},bf:{openness:.76,conscientiousness:.72,extraversion:.52,agreeableness:.22,neuroticism:.34},bias:['overconfidence','framing','in-group'],
  entry:['accumulates governance tokens ahead of contested votes','buys influence where the float is thin','positions before proposals it helped draft'],
  stress:['forces the vote when attention is lowest','trades the treasury outcome it lobbied for','exits governance the block after the win'],
  tell:['reads forums like order flow','collects delegates the way others collect yield','frames every raid as alignment']},
 // --- whale / institutional ---
 {tag:'otc-block-desk',theme:'whale',style:'deliberative',lam:2.4,dt:{m:.66,n:.38,p:.30},bf:{openness:.60,conscientiousness:.88,extraversion:.40,agreeableness:.42,neuroticism:.24},bias:['anchoring','information-bias'],
  entry:['works size off-exchange in negotiated blocks','splits the parent order across venues and days','prices urgency into every counterparty quote'],
  stress:['goes quiet and lets the tape come back','leans on relationships when the screen dries up','hedges the residual and reports the slippage honestly'],
  tell:['thinks in basis points of impact','never posts the real size','treats information leakage as the only true loss']},
 {tag:'basis-cash-carry',theme:'whale',style:'analytical',lam:2.2,dt:{m:.54,n:.30,p:.24},bf:{openness:.62,conscientiousness:.90,extraversion:.32,agreeableness:.46,neuroticism:.26},bias:['pseudocertainty','status-quo'],
  entry:['puts on the cash-and-carry when the curve pays','sizes to funding stress, not to conviction','rolls the front month like clockwork'],
  stress:['survives the squeeze by being under-levered on purpose','unwinds early rather than explain a margin call','re-checks counterparty risk before re-checking price'],
  tell:['describes euphoria as a widening basis','keeps the excitement in a spreadsheet','calls directional views a hobby']},
 {tag:'protocol-treasury-manager',theme:'whale',style:'deliberative',lam:2.8,dt:{m:.44,n:.28,p:.16},bf:{openness:.58,conscientiousness:.86,extraversion:.38,agreeableness:.58,neuroticism:.32},bias:['omission','status-quo','ambiguity-aversion'],
  entry:['deploys treasury in laddered, boring tranches','diversifies the runway before chasing yield','writes the investment policy before the first trade'],
  stress:['freezes discretionary deployment at the first depeg headline','reports bad marks early and in full','holds stables through the storm and takes the inflation criticism'],
  tell:['answers to a forum thread, and acts like it','measures success in months of runway','treats every basis point as someone’s grant']},
 {tag:'liquidation-backstop-bot',theme:'whale',style:'analytical',lam:1.6,dt:{m:.60,n:.20,p:.40},bf:{openness:.55,conscientiousness:.96,extraversion:.12,agreeableness:.20,neuroticism:.08},bias:['action-bias','clustering-illusion'],
  entry:['bids the cascade with pre-committed capital','prices panic in real time and buys it','keeps dry powder precisely for the worst hour of the year'],
  stress:['executes the backstop ladder without hesitation','absorbs inventory at spreads no human would quote','stands down the moment volatility normalizes'],
  tell:['has no feelings about the asset whatsoever','books the same trade every crisis','treats mercy and spread as the same parameter']},
 // --- negotiation counterparties ---
 {tag:'hardline-procurement',theme:'negotiation',style:'analytical',lam:2.2,dt:{m:.68,n:.36,p:.34},bf:{openness:.46,conscientiousness:.82,extraversion:.48,agreeableness:.24,neuroticism:.34},bias:['anchoring','framing','zero-risk'],
  entry:['opens with a benchmark study and a haircut','demands the cost breakdown before the meeting','treats every quote as the ceiling of a long descent'],
  stress:['escalates to the competing bid on cue','re-tenders the contract to reset the anchor','trades volume promises it may not keep'],
  tell:['knows your margin better than your sales rep does','keeps a discount matrix laminated','ends meetings exactly on time as a message']},
 {tag:'deadline-bluffer',theme:'negotiation',style:'intuitive',lam:1.7,dt:{m:.72,n:.56,p:.48},bf:{openness:.62,conscientiousness:.50,extraversion:.66,agreeableness:.32,neuroticism:.44},bias:['framing','overconfidence','confabulation'],
  entry:['manufactures urgency with a straight face','sets expiries designed to be extended','opens every round with a clock nobody audited'],
  stress:['lets the fake deadline lapse and renames it','invents a competing party with plausible detail','escalates theatrics before substance'],
  tell:['checks their watch as punctuation','has three final offers per deal','confuses momentum with leverage, profitably']},
 {tag:'relationship-banker',theme:'negotiation',style:'dependent',lam:2.3,dt:{m:.52,n:.48,p:.24},bf:{openness:.54,conscientiousness:.66,extraversion:.72,agreeableness:.74,neuroticism:.40},bias:['in-group','endowment','peak-end'],
  entry:['prices the decade, not the deal','gives the first concession as a gift with a memory','opens with lunch and closes with a favor'],
  stress:['calls in goodwill instead of lawyers','absorbs a bad quarter to keep the account','over-services the relationship at the margin’s expense'],
  tell:['remembers your kids’ names and your break clauses','files every dinner as diligence','believes churn is a character flaw']},
 {tag:'silent-closer',theme:'negotiation',style:'deliberative',lam:2.0,dt:{m:.64,n:.30,p:.36},bf:{openness:.56,conscientiousness:.78,extraversion:.26,agreeableness:.36,neuroticism:.28},bias:['anchoring','information-bias'],
  entry:['says less each round on purpose','lets the other side negotiate against themselves','asks one question and writes down the whole answer'],
  stress:['sits through silence that breaks the other chair first','answers ultimatums with scheduling','concedes only what was budgeted for concession'],
  tell:['pauses long enough to be quoted','treats every disclosure as a purchase','keeps the walk-away number in a sealed envelope, literally']},
 {tag:'winwin-idealist',theme:'negotiation',style:'dependent',lam:2.5,dt:{m:.30,n:.40,p:.16},bf:{openness:.70,conscientiousness:.60,extraversion:.62,agreeableness:.82,neuroticism:.48},bias:['optimism','halo-effect','false-consensus'],
  entry:['opens with the joint-value speech, sincerely','shares information first to model the norm','designs the term sheet around the relationship chart'],
  stress:['keeps collaborating while being harvested','reframes exploitation as a misunderstanding twice before believing it','concedes on price to protect the principle'],
  tell:['says "expand the pie" without irony','measures deals in referrals','is owed favors across three industries and collects none']},
 {tag:'attrition-grinder',theme:'negotiation',style:'deliberative',lam:1.9,dt:{m:.74,n:.42,p:.44},bf:{openness:.48,conscientiousness:.84,extraversion:.44,agreeableness:.26,neuroticism:.36},bias:['sunk-cost','escalation-of-commitment','anchoring'],
  entry:['schedules more rounds than the deal needs, on purpose','reopens settled clauses at intervals','sends the long redline late on Fridays'],
  stress:['wins by making agreement the cheaper exit','absorbs delay costs better than the other side, and knows it','trades nothing until exhaustion sets the price'],
  tell:['version numbers in the teens','celebrates stamina like a metric','considers fatigue a legitimate clause']},
 // --- KOL / influence ---
 {tag:'contrarian-caller',theme:'kol',style:'intuitive',lam:1.5,dt:{m:.62,n:.74,p:.46},bf:{openness:.78,conscientiousness:.44,extraversion:.70,agreeableness:.28,neuroticism:.50},bias:['overconfidence','hindsight','confabulation'],
  entry:['calls the top the whole way up','brands every consensus a trap','posts the lonely take for the quote-posts'],
  stress:['screenshots the one nailed call from 2021, again','reframes the miss as early','doubles the conviction when the audience wavers'],
  tell:['profit is engagement, positions optional','archives losses, pins wins','writes "few understand" unironically']},
 {tag:'thread-educator',theme:'kol',style:'analytical',lam:2.1,dt:{m:.44,n:.56,p:.22},bf:{openness:.80,conscientiousness:.76,extraversion:.56,agreeableness:.60,neuroticism:.38},bias:['curse-of-knowledge','confirmation','optimism'],
  entry:['turns every position into a 14-part explainer','teaches the mechanism and discloses the bag, usually','builds the audience a mental model and a watchlist'],
  stress:['posts the correction thread with charts and no apology needed','over-explains the drawdown until it sounds planned','mistakes a clear explanation for a correct one'],
  tell:['diagrams first, position second','answers replies at 1am with sources','has a pinned glossary and a merch store']},
 {tag:'engagement-farmer',theme:'kol',style:'spontaneous',lam:1.3,dt:{m:.78,n:.70,p:.56},bf:{openness:.68,conscientiousness:.36,extraversion:.84,agreeableness:.30,neuroticism:.52},bias:['bandwagon','gaze-heuristic','recency'],
  entry:['posts whichever take is trending against','runs polls engineered to be screenshotted','manufactures beef on slow news days'],
  stress:['deletes quietly and reposts louder','pivots niches inside a week','monetizes the apology'],
  tell:['metrics dashboard open during dinner','opinions have a posting schedule','remembers ratios, forgets positions']},
 {tag:'quiet-builder-voice',theme:'kol',style:'deliberative',lam:2.2,dt:{m:.34,n:.40,p:.18},bf:{openness:.76,conscientiousness:.80,extraversion:.40,agreeableness:.62,neuroticism:.34},bias:['curse-of-knowledge','in-group','omission'],
  entry:['ships first, posts second','announces in changelogs, not threads','lets the demo do the marketing'],
  stress:['goes heads-down when the timeline melts','answers FUD with a commit link','underexplains and gets misquoted for it'],
  tell:['follower count flat, reply quality absurd','allergic to price talk','deletes drafts that sound like hype']},
];

// ---------------------------------------------------------------------------
// V3 repair banks — one entry per template archetype from populate-v3-dataset.
// detect: tags that uniquely identify the archetype among v3 rows.
// clauses/decisions are picked at SQL-emit time from the live synth banks.
// biases: [slug, baseStrength] triples used to rebuild suggested_biases.
// ---------------------------------------------------------------------------
const V3_REPAIR = [
 {arch:'pump-fun-sniper', group:'degen', detect:['pump-fun'], style:'intuitive',
  roles:['pump.fun first-block sniper','memecoin launch sniper','new-pair momentum sniper'],
  habits:['buys the ticker before the website exists','pays priority fees like a cover charge','rides the vertical candle with the exit pre-typed'],
  tells:['measures conviction in seconds, not theses','keeps a graveyard wallet of rugs as tuition','narrates every 10x and deletes every zero'],
  biases:[['fomo',0.78],['overconfidence',0.62],['recency',0.55]]},
 {arch:'raydium-lp-arb', group:'inst', detect:['raydium-trader'], style:'analytical',
  roles:['Raydium pool arbitrageur','AMM spread harvester','cross-pool basis picker'],
  habits:['skims mispriced pools with pre-signed routes','sizes by pool depth and fee tier, never by mood','rebalances inventory the moment skew appears'],
  tells:['treats slippage as the only enemy worth respecting','keeps the excitement in a log file','quotes fee APRs to the second decimal'],
  biases:[['overconfidence',0.55],['zero-risk',0.52],['anchoring',0.45]]},
 {arch:'jupiter-rotator', group:'degen', detect:['jupiter-trader'], style:'spontaneous',
  roles:['Jupiter route rotator','aggregator hopper','narrative rotation trader'],
  habits:['rotates the whole stack when the meta shifts','routes through whatever venue prints best this hour','holds nothing long enough to name it'],
  tells:['portfolio turnover reads like a seismograph','loyal to routes, not tokens','always mid-swap when asked for an opinion'],
  biases:[['recency',0.68],['action-bias',0.6],['fomo',0.5]]},
 {arch:'solana-perps-degen', group:'degen', detect:['solana-perps'], style:'intuitive',
  roles:['100x perps degen','max-leverage cliff diver','funding-be-damned perps gunslinger'],
  habits:['opens max leverage on a chart pattern and a feeling','treats liquidation price as a suggestion','adds margin at 3am instead of sleeping'],
  tells:['account equity is a heartbeat monitor','celebrates surviving as if it were winning','knows the liquidation engine personally'],
  biases:[['overconfidence',0.8],['illusion-of-control',0.66],['gamblers-fallacy',0.58]]},
 {arch:'solana-nft-flipbot', group:'degen', detect:['solana-nft'], style:'deliberative',
  roles:['NFT floor-sweep flipper','mint-and-flip operator','collection rotation bot-runner'],
  habits:['sweeps thin floors and relists in tranches','mints on schedule and exits into the reveal','tracks rarity spreads like a bond desk'],
  tells:['gallery full of inventory, none of it loved','values liquidity over provenance','refreshes floor prices between sentences'],
  biases:[['endowment',0.5],['recency',0.6],['availability',0.5]]},
 {arch:'zero-dte-gambler', group:'retail', detect:['zero-dte'], style:'intuitive',
  roles:['0DTE options gambler','same-day expiry gunslinger','theta-be-damned lottery player'],
  habits:['buys the morning lotto ticket at the open','sizes by adrenaline and yesterday’s result','holds through the last hour for the miracle'],
  tells:['win rate quoted, sizing omitted','remembers the 30-bagger, forgets the forty zeros','checks the chain before checking the news'],
  biases:[['gamblers-fallacy',0.72],['overconfidence',0.68],['availability',0.55]]},
 {arch:'meme-stock-hodler', group:'retail', detect:['meme-stock'], style:'intuitive',
  roles:['meme-stock true believer','squeeze-thesis lifer','diamond-handed basket holder'],
  habits:['buys every dip of the same three tickers','holds through halts on principle','averages down as an act of faith'],
  tells:['cost basis is a loyalty badge','distrusts every institution except the forum','celebrates red days as shakeouts'],
  biases:[['sunk-cost',0.74],['endowment',0.66],['confirmation',0.6]]},
 {arch:'retail-panic-seller', group:'retail', detect:['loss-averse','avoidant'], style:'avoidant',
  roles:['retail panic seller','drawdown capitulator','flight-response trader'],
  habits:['buys calm and sells storm, reliably','liquidates first and reads the headline after','sits in cash until the fear fades, then rebuys higher'],
  tells:['portfolio history is a seismogram of scares','asks for reassurance, trades before it arrives','sleeps in cash, regrets in rallies'],
  biases:[['loss-aversion',0.85],['ostrich-effect',0.6],['negativity',0.55]]},
 {arch:'retail-swing-discipline', group:'retail', detect:['swing-trader'], style:'deliberative',
  roles:['disciplined retail swing trader','plan-first position trader','checklist swing operator'],
  habits:['enters on the setup, not the story','journals entries before placing them','takes the stop like a professional expense'],
  tells:['boring on purpose and proud of it','equity curve smoother than their commute','reviews losers on Sundays, calmly'],
  biases:[['anchoring',0.5],['confirmation',0.48]]},
 {arch:'sentiment-follower', group:'retail', detect:['social-trader'], style:'dependent',
  roles:['social-sentiment follower','feed-driven retail trader','consensus surfer'],
  habits:['buys what the timeline agrees on','waits for three influencers to align before entering','exits when the group chat goes quiet'],
  tells:['conviction is crowdsourced hourly','always one candle behind the narrative','holds only what is popular to hold'],
  biases:[['herd-behavior',0.76],['bandwagon',0.64],['authority-bias',0.5]]},
 {arch:'whale-market-maker', group:'inst', detect:['market-maker'], style:'analytical',
  roles:['whale market maker','two-sided liquidity desk','spread-capture operator'],
  habits:['quotes both sides and lives in the spread','widens ruthlessly when toxicity rises','recycles inventory before it becomes opinion'],
  tells:['has no favorite direction, only favorite volatility','measures the day in fill quality','goes flat for the night like clockwork'],
  biases:[['zero-risk',0.5],['anchoring',0.45]]},
 {arch:'mev-searcher', group:'inst', detect:['mev-searcher'], style:'analytical',
  roles:['MEV sandwich searcher','mempool opportunist','priority-auction predator'],
  habits:['hunts the mempool for mispriced intent','bids the priority auction to the edge of profit','simulates the bundle twice and lands it once'],
  tells:['counts profit in microseconds of advantage','feels nothing about the counterparty, ever','iterates the bot nightly like a craftsman'],
  biases:[['overconfidence',0.6],['action-bias',0.58]]},
 {arch:'macro-hedger', group:'inst', detect:['macro-hedger'], style:'analytical',
  roles:['institutional macro hedger','tail-risk allocator','regime-change insurance buyer'],
  habits:['pays steady premium for the bad day','sizes hedges to the balance sheet, not the mood','rolls protection on calendar, not conviction'],
  tells:['sounds pessimistic, positions symmetric','celebrates the hedge expiring worthless','reads central-bank minutes for tone shifts'],
  biases:[['ambiguity-aversion',0.6],['zero-risk',0.55],['pessimism',0.5]]},
 {arch:'defi-yield-whale', group:'inst', detect:['yield-optimizer'], style:'deliberative',
  roles:['DeFi yield whale','protocol-scale liquidity allocator','risk-tranched yield optimizer'],
  habits:['moves nine figures between protocols on a risk score','ladders exposure across audits and insurance','negotiates private rates the interface never shows'],
  tells:['reads smart-contract diffs at breakfast','counts yield after every haircut imaginable','exits a week before the incident, usually'],
  biases:[['status-quo',0.45],['ambiguity-aversion',0.55],['pseudocertainty',0.5]]},
 {arch:'hft-liquidation-bot', group:'inst', detect:['hft-bot'], style:'analytical',
  roles:['autonomous liquidation engine','cascade-hour execution bot','forced-flow harvester'],
  habits:['prices panic without feeling it','executes the ladder the humans pre-committed','absorbs forced sellers at spreads no desk would quote'],
  tells:['uptime is its only mood','books the same trade every crisis','has no narrative, only parameters'],
  biases:[['action-bias',0.5],['clustering-illusion',0.4]]},
];

module.exports = { LEGACY_ARCH, NEW_ARCH, V3_REPAIR };
