-- 0021_bias_examples_mitigations.sql
-- Fixes the cognitive-bias-simulator preview/query and fills the content the
-- product advertises ("worked examples, mitigations") but never shipped.
--
-- ROOT-CAUSE (preview 500): previewBiases()/resolveBiasQuery() are the only code
-- paths that SELECT biases.examples / biases.mitigations. If a deployed DB's
-- biases table predates those columns (schema drift), PostgREST 500s that
-- product's preview while every other product works. ADD COLUMN IF NOT EXISTS
-- makes the columns certain to exist; the upsert then populates real content.
-- Idempotent and safe to re-run.

ALTER TABLE biases ADD COLUMN IF NOT EXISTS examples    jsonb NOT NULL DEFAULT '[]';
ALTER TABLE biases ADD COLUMN IF NOT EXISTS mitigations jsonb NOT NULL DEFAULT '[]';

INSERT INTO biases (slug, name, description, source, examples, mitigations) VALUES
  ('loss-aversion', 'Loss Aversion', 'Losses loom larger than equivalent gains', 'Kahneman & Tversky (1979)', '["A trader holds a losing position far past their stop because realizing the loss hurts more than the paper drawdown.","An agent rejects a +EV bet with any downside, over-weighting the possible loss versus the larger expected gain."]'::jsonb, '["Pre-commit exits (hard stops) before entering, and evaluate positions on expected value, not entry price.","Frame decisions in terms of total portfolio outcome rather than per-position gain/loss."]'::jsonb),
  ('fomo', 'Fear of Missing Out', 'Anxiety-driven action to avoid missing rewarding experiences', 'Przybylski et al. (2013)', '["A retail trader chases a coin already up 300% because everyone on the feed is posting gains.","An agent front-runs its own risk rules to enter a parabolic move rather than watch it run without them."]'::jsonb, '["Require a written thesis and risk budget before any entry; no thesis, no trade.","Use a cooldown timer on impulse entries and size chase-trades at a fraction of normal risk."]'::jsonb),
  ('anchoring', 'Anchoring', 'Over-reliance on the first number or fact encountered', 'Tversky & Kahneman (1974)', '["A buyer treats the 52-week high as \"cheap now\" even after fundamentals changed.","A negotiator lets an absurd opening offer quietly set the entire bargaining range."]'::jsonb, '["Estimate fair value independently before seeing any quoted price or opening offer.","Force a second, from-scratch valuation and reconcile it against the anchored one."]'::jsonb),
  ('sunk-cost', 'Sunk Cost Fallacy', 'Continuing investment to justify past investment', 'Arkes & Blumer (1985)', '["An investor adds to a failing position \"to average down\" mainly to justify the money already committed.","A team keeps funding a doomed project because of how much has already been spent."]'::jsonb, '["Decide from marginal forward value only; ask \"would I open this today at this price?\"","Set predefined abandon criteria for positions and projects at the outset."]'::jsonb),
  ('confirmation', 'Confirmation Bias', 'Seeking evidence that supports existing beliefs', 'Nickerson (1998)', '["A trader reads only the bullish theses for a bag they already hold and dismisses the bearish data as noise.","An agent queries only sources likely to agree with its current position."]'::jsonb, '["Actively seek the strongest disconfirming evidence and assign someone to argue the other side.","Write the falsification condition before committing to a thesis."]'::jsonb),
  ('overconfidence', 'Overconfidence', 'Certainty exceeding actual accuracy', 'Moore & Healy (2008)', '["A trader sizes 40% of the book into one idea, certain of a call the track record does not support.","An agent reports 95% confidence on estimates that are right barely 60% of the time."]'::jsonb, '["Track calibration: log predicted probabilities and compare to realized hit rates.","Cap single-idea position size and widen confidence intervals by default."]'::jsonb),
  ('herd-behavior', 'Herd Behavior', 'Following crowd actions over private information', 'Banerjee (1992)', '["A trader abandons a well-researched short the moment the timeline turns euphoric.","An agent copies the consensus trade and discards its own contrary signal."]'::jsonb, '["Record your private signal before viewing the crowd, and weight it explicitly.","Reward independent correct calls over consensus-following in the review process."]'::jsonb),
  ('availability', 'Availability Heuristic', 'Judging likelihood by ease of recall', 'Tversky & Kahneman (1973)', '["After one vivid rug-pull headline, a trader over-estimates the odds of every new token being a scam.","An agent weights a recent memorable event as typical, ignoring the base rate."]'::jsonb, '["Anchor likelihoods to base rates and historical frequencies, not recent vivid events.","Keep a reference table of long-run probabilities to consult under stress."]'::jsonb),
  ('recency', 'Recency Bias', 'Overweighting the most recent observations', 'Murdock (1962)', '["A trader extrapolates a three-day rally into a permanent trend and sizes up into it.","An agent assumes the current volatility regime will persist indefinitely."]'::jsonb, '["Use longer lookback windows and regime-aware models rather than the last few observations.","Explicitly test whether the recent trend is signal or noise before extrapolating."]'::jsonb),
  ('disposition-effect', 'Disposition Effect', 'Selling winners early, holding losers long', 'Shefrin & Statman (1985)', '["A trader banks a +8% winner immediately but holds a -40% loser \"until it comes back\".","An agent realizes small gains fast while letting losses run past any risk limit."]'::jsonb, '["Apply symmetric rules: same trailing-stop / take-profit logic to winners and losers.","Judge each holding on forward expected value, ignoring whether it is currently green or red."]'::jsonb),
  ('status-quo', 'Status Quo Bias', 'Preferring the current state over change', 'Samuelson & Zeckhauser (1988)', '["An investor stays 100% in cash through a clear setup because doing nothing feels safer than acting.","An agent keeps its default allocation even when the evidence favors rebalancing."]'::jsonb, '["Treat \"do nothing\" as an active choice that must clear the same bar as any alternative.","Schedule periodic forced rebalancing so inaction cannot win by default."]'::jsonb),
  ('endowment', 'Endowment Effect', 'Valuing owned things above market value', 'Thaler (1980)', '["A holder refuses to sell a token at a price they would never pay to buy it back.","An agent overvalues assets already in its portfolio versus identical ones outside it."]'::jsonb, '["Ask the buy-back test: at this price, would I acquire this if I did not already hold it?","Mark to market and evaluate holdings as if the portfolio were rebuilt from cash."]'::jsonb),
  ('hindsight', 'Hindsight Bias', 'Seeing past events as having been predictable', 'Fischhoff (1975)', '["After a crash a trader insists they \"knew it was a top\", rewriting their own prior uncertainty.","An agent logs a surprising outcome as foreseeable, corrupting its own calibration data."]'::jsonb, '["Keep a decision journal recording the reasoning and confidence at the time of the call.","Score decisions on process quality given what was knowable, not on the outcome."]'::jsonb),
  ('optimism', 'Optimism Bias', 'Underestimating personal risk of negative events', 'Sharot (2011)', '["A leveraged trader assumes liquidation risk applies to everyone else but not to their position.","An agent under-provisions for a tail risk it can accurately describe for others."]'::jsonb, '["Run an explicit pre-mortem: assume the position blew up and enumerate how.","Size for the tail scenario you would warn a peer about, not the base case."]'::jsonb),
  ('framing', 'Framing Effect', 'Different choices from equivalent presentations', 'Tversky & Kahneman (1981)', '["A trader accepts \"90% win rate\" but rejects the identical \"10% chance of ruin\" framing.","An agent flips its decision based purely on whether an outcome is worded as a gain or a loss."]'::jsonb, '["Restate every choice in both gain and loss framings and require the same decision.","Convert options to a common absolute-outcome metric before deciding."]'::jsonb),
  ('gamblers-fallacy', 'Gambler''s Fallacy', 'Expecting reversal after streaks in independent events', 'Tversky & Kahneman (1971)', '["After five red candles a trader bets big on green because a bounce \"is due\".","An agent treats independent draws as if they owe a reversal."]'::jsonb, '["Treat independent events as memoryless; never size up on a \"due\" reversal.","Base position sizing on the actual model edge, not on streak length."]'::jsonb),
  ('ostrich-effect', 'Ostrich Effect', 'Avoiding negative information exposure', 'Galai & Sade (2006)', '["A trader stops checking the portfolio during a drawdown, delaying the decision that would help most.","An agent skips the health-check it most needs to run when signals look bad."]'::jsonb, '["Automate monitoring and alerts so bad news is surfaced whether or not you look.","Schedule mandatory reviews precisely for drawdown conditions."]'::jsonb),
  ('bandwagon', 'Bandwagon Effect', 'Adopting beliefs because many others hold them', 'Leibenstein (1950)', '["A trader gains conviction in a thesis purely in proportion to how many others post it.","An agent adopts a position once it stops being a minority view, regardless of evidence."]'::jsonb, '["Weigh the argument, not the head-count; count evidence, not adopters.","Seek a credible dissenter before joining a popular position."]'::jsonb),
  ('authority-bias', 'Authority Bias', 'Overweighting authority figures'' opinions', 'Milgram (1963)', '["A trader overrides their own model because a well-known influencer said otherwise.","An agent defers to a credentialed-sounding source over its own verified data."]'::jsonb, '["Require authority claims to be backed by verifiable data before overriding your model.","Separate the messenger from the message; evaluate the argument blind to its source where possible."]'::jsonb),
  ('dunning-kruger', 'Dunning–Kruger Effect', 'Low ability paired with inflated self-assessment', 'Kruger & Dunning (1999)', '["A new options trader is most certain exactly where their understanding is thinnest.","An agent reports high competence on a task class it systematically fails."]'::jsonb, '["Calibrate against objective benchmarks and external review, not self-assessment.","Widen uncertainty and reduce size in domains of limited track record."]'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name        = EXCLUDED.name,
  description  = EXCLUDED.description,
  source       = EXCLUDED.source,
  examples     = EXCLUDED.examples,
  mitigations  = EXCLUDED.mitigations;
